name: 'dbt_click'
version: '1.0.0'

profile: 'dbt_click'

model-paths: ["models"]

models:
  dbt_click:
    orders_stream_cur:
      +materialized: view
      +on_schema_change: ignore
      +persist_docs.relation: false